### ISSUE TITLE
Device not compatible with google services AR

### ISSUE THREAD

**Issue by Liliana99** [giandifra/arcore_flutter_plugin#11]
I had tried  to install the my demo_app usign the plugin ar_core_flutter  on my device BQ then on Google Play Services AR, saids my device is not compatible with this versión!!, the Android System on my device is 8.1.0.

Then I try to install on Galaxy Tab A(2016) SM-T580 Android versión 8.1.0 the result was the same => 'Device  is not compatible '

**Comment by ukeOnFire** [comment]
https://developers.google.com/ar/discover/supported-devices

I am, too, troubled that my BQ device is not compatible. However, you can get it to work on an emulator.

**Comment by giandifra** [comment]
To verify from new update you can use: 
`final bool isCompatibleWithArcore =
      await ArCoreController.checkArCoreAvailability();`

**Comment by krishnaaro** [comment]
`final bool isCompatibleWithArcore = await ArCoreController.checkArCoreAvailability();`

Seems the above not available in arcore_flutter_plugin 0.0.5+1 (latest one till date).

and seems App crashing in unsupported mobile devices, even in example App.

need Assist, Please.
