### ISSUE TITLE
ArCoreView.kt: (241, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated

### ISSUE THREAD

**Issue by sikandernoori** [giandifra/arcore_flutter_plugin#130]
ArCoreView.kt: (241, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated

**Comment by Emex4gman** [comment]
@sikandernoori  how did you resolve this, am still getting this issue

**Comment by sikandernoori** [comment]
Yes I did !

the Issue was with Null Safety !

Upgrade Your Code to Null Safety or a little Modification in Plugin.

I would recommend Upgrading Your Code to Null Safety.

**Comment by sikandernoori** [comment]
> @sikandernoori how did you resolve this, am still getting this issue

Yes I did !

the Issue was with Null Safety !

Upgrade Your Code to Null Safety or a little Modification in Plugin.

I would recommend Upgrading Your Code to Null Safety.

**Comment by Emex4gman** [comment]
@sikandernoori 
I just did, and i ran flutter clean 
but same error, 
and the project is a new project, no other package

**Comment by Emex4gman** [comment]
![image](https://user-images.githubusercontent.com/23434595/117097123-c7fdb980-ad38-11eb-9641-5fe4380af27b.png)

**Comment by Emex4gman** [comment]
![image](https://user-images.githubusercontent.com/23434595/117097150-d946c600-ad38-11eb-973c-1e7b77d35de6.png)

**Comment by sikandernoori** [comment]
Not Sure. Ping me @sikandernoori Skype and I can Take a Look.
