### ISSUE TITLE
 'onActivityCreated' overrides nothing

### ISSUE THREAD

**Issue by sn9854d** [giandifra/arcore_flutter_plugin#148]
../arcore_flutter_plugin-0.0.11/android/src/main/kotlin/com/difrancescogianmarco/arcore_flutter_plugin/ArCoreView.kt: (245, 38): 
Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(@NonNull p0: Activity, @Nullable p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks

**Comment by jyashi** [comment]
Did you find a solution to this? I am having same issue
