### ISSUE TITLE
I can't use the plugin in a device with ArCore installed

### ISSUE THREAD

**Issue by alejandrogiubel** [giandifra/arcore_flutter_plugin#155]
I have a Samsung Galaxy A30 and its have installed ArCore. When I run the plugin it send me to Google play to install the ArCore service but I have installed. I check this two variables 

> ArCoreController.checkArCoreAvailability()

and

> ArCoreController.checkIsArCoreInstalled();

`ArCoreController.checkArCoreAvailability()` `return true` and `ArCoreController.checkIsArCoreInstalled();` `return false`.

What can I do?
Thank

**Comment by alejandrogiubel** [comment]
I solve the problem change the `compileSdkVersion` and `targetSdkVersion` from 30 to 29. Maybe sombre problem in Api 30.

**Comment by avikdutta111191** [comment]
> 

Tried that to didn't work

**Comment by avikdutta111191** [comment]
> I have a Samsung Galaxy A30 and its have installed ArCore. When I run the plugin it send me to Google play to install the ArCore service but I have installed. I check this two variables
> 
> > ArCoreController.checkArCoreAvailability()
> 
> and
> 
> > ArCoreController.checkIsArCoreInstalled();
> 
> `ArCoreController.checkArCoreAvailability()` `return true` and `ArCoreController.checkIsArCoreInstalled();` `return false`.
> 
> What can I do? Thank

getting same result in target and comile SDK 31 too

**Comment by larsien** [comment]
`ArCoreController.checkIsArCoreInstalled();`
targetSdkVersion 31,30 still failed to run. 
But succeeded on 29
