### ISSUE TITLE
can you create arkit for andriod as well?

### ISSUE THREAD

**Issue by iamprakash13** [giandifra/arcore_flutter_plugin#17]
like all fucntions of arkit in android https://github.com/olexale/arkit_flutter_plugin

image tracking n etc

please make plugin it helps a lot.

**Comment by giandifra** [comment]
Hi, i'm working to implement [Augmented Faces](https://developers.google.com/ar/develop/java/augmented-faces) of ArCore.  
I hope to implement all available feature.
