### ISSUE TITLE
arcore_flutter_plugin:compileDebugKotlin

### ISSUE THREAD

**Issue by Seung-hwan285** [giandifra/arcore_flutter_plugin#176]
e: C:\Users\User\Downloads\flutter_windows_2.10.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (245, 38): Object is not abstract and does not implement abstract member public abstract fun onActivityCreated(p0: Activity, p1: Bundle?): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: C:\Users\User\Downloads\flutter_windows_2.10.3-stable\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArCoreView.kt: (246, 13): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
> Compilation error. See log for more details

Is there any workaround for this error?
I haven't been able to start the project for a week.

**Comment by alegos27** [comment]
I faced this issue after updating to flutter 3

Solved with downgrade to flutter 2.10.5

**Comment by Seung-hwan285** [comment]
I saw this and fixed it  
https://github.com/giandifra/arcore_flutter_plugin/issues/149
