### ISSUE TITLE
(Question) Does this plugin support iOS Platform?

### ISSUE THREAD

**Issue by dannycortesv** [giandifra/arcore_flutter_plugin#18]
Didn't find any reference to it, so can you guys help me know if this plugin support iOS Platform? Thanks

**Comment by calvyntwh** [comment]
i would like to know as well

**Comment by anirudhsharma392** [comment]
No, for iOS you can use this :
https://pub.dev/packages/arkit_plugin

**Comment by giandifra** [comment]
AR Core SDK is available for ios too, I will implement ios side in the future (I have little free time now)

**Comment by Yacine-Benali** [comment]
@giandifra I would love to know if there is any update on this one, as it would be great to have the plugin be cross-platform.
thank you for the great work, am very grateful for it

**Comment by giandifra** [comment]
Hi, it's not into my todo list for now, i'm very busy! I think there will be changes about ArCore native SDK...maybe is better waiting to implement last native sdk.

Thanks

**Comment by dariocavada** [comment]
@Yacine-Benali I use both ArCore for Android and https://pub.dev/packages/arkit_plugin for iOS.
I created 2 Screen (one for Android (ARCoreScreen) and one for iOS (ARKitScreen) and then I show one or the other view according to the platform ... obviously ARCore and ARKit are different and therefore it is necessary to create the two implementations in a different way.

The following snippet check if the Augmented Reality is supported by the device and return the appropriate screen:

``` dart
 /// Show the right Augmented Reality Screen Type
    /// or nothing if not supported by the underlying platform
    Widget _arKitOrArCore() {
      if (Theme.of(context).platform == TargetPlatform.android) {
        // ARCore Android
        return ARCoreScreen();
      } else if (Theme.of(context).platform == TargetPlatform.iOS) {
        // ARKit iOS
        return ARKitScreen();
      } else {
        return Container(
          width: 150.00,
          padding: EdgeInsets.fromLTRB(20, 20, 20, 20),
          color: Colors.blueAccent,
          child: Text(
            'AR Not supported',
            textAlign: TextAlign.center,
            style: TextStyle(fontSize: 24, color: Colors.white),
          ),
        );
      }
    }
```

**Comment by Yacine-Benali** [comment]
@dariocavada yes thats what I was thinking of doing, the thing is that I am using ARcore for face tracking and ARkit face tracking only supports iPhone X and later and I wanted to support some older models, most probably will end up creating a native screen within the flutter app but I got to learn some swift first.
anyways thanks for the code snippet.

**Comment by jpirovano** [comment]
Guys, I think you should warn in the readme that it doesn't support iOS, I lost 30min configuring it to find out

**Comment by Askhento** [comment]
what is the status?
