### ISSUE TITLE
[ arcore_flutter_plugin 0.1.0-null-safety.3 ] I have no idea what is this

### ISSUE THREAD

**Issue by jintop-coder** [giandifra/arcore_flutter_plugin#187]
![Screenshot 2022-07-05 165654](https://user-images.githubusercontent.com/75776202/177317473-5717b8c1-2352-440e-b4d5-f2c7d88007c9.png)

I have no idea what is this............? , I think it came from plugin side arcore_flutter_plugin 0.1.0-null-safety.3 , 

and i don't konw the platform side to access the android native code using method channel so how to access it ....?

**Comment by giandifra** [comment]
Closed via #200
