### ISSUE TITLE
Gradle Error !!!!!

### ISSUE THREAD

**Issue by kbattulwar** [giandifra/arcore_flutter_plugin#197]
Hi,
I  have tried every method in my knowledge to fixz this error. Does anyone know how can i overcome this?
Will really appreciate your I  have tried every method in my knowledge to fixz this error. Does anyone know how can i overcome this?
Will really appreciate your help at this moment.help at this moment.

Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
e: C:\Users\kbattulwar\_DevProjects\ar\arcore_flutter_plugin-master\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArcoreFlutterPlugin.kt: (32, 74): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by DomasB** [comment]
I am having an exact same issue. Flutter v3.3.9

**Comment by giandifra** [comment]
Hi, I fixed this, can you try the new branch? #200

**Comment by giandifra** [comment]
Closed via #200
