### ISSUE TITLE
Type mismatch: inferred type is Activity? but Activity was expected

### ISSUE THREAD

**Issue by geopardaz** [giandifra/arcore_flutter_plugin#199]
I set all the configurations as you said in the package and medium lecture but I got this Error. also the other got this Error so. 
please fix this or help how to solve this problem. my flutter version is 3.3

e: E:\flutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\arcore_flutter_plugin-0.0.11\android\src\main\kotlin\com\difrancescogianmarco\arcore_flutter_plugin\ArcoreFlutterPlugin.kt: (32, 74): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Juanca0312** [comment]
same issue @giandifra

**Comment by vishalvishvakarma1111** [comment]
Same error


e: /Users/macos/tools/flutter/.pub-cache/hosted/pub.dartlang.org/arcore_flutter_plugin-0.0.11/android/src/main/kotlin/com/difrancescogianmarco/arcore_flutter_plugin/ArcoreFlutterPlugin.kt: (32, 74): Type mismatch: inferred type is Activity? but Activity was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':arcore_flutter_plugin:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by giandifra** [comment]
Hi, what branch are you using?

**Comment by giandifra** [comment]
I fixed the error, can you try the new branch? #200

**Comment by PiotrMitkowski** [comment]
Hello @giandifra! I got the same issue and can confirm that your fix works properly.

**Comment by giandifra** [comment]
Closed via #200
