### ISSUE TITLE
Sample project crash

### ISSUE THREAD

**Issue by MoSamir** [giandifra/arcore_flutter_plugin#20]
Sample Project not working crashes when opening any AR screen with stack trace 

I/hwaps   (  570): JNI_OnLoad
V/AudioManager(  570): playSoundEffect   effectType: 0
E/BufferQueueProducer(  570): [] Can not get hwsched service
D/HwCust  (  570): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
I/Filament(  570): FEngine (64 bits) created at 0x7504400000 (threading is enabled)
D/Filament(  570): FEngine resolved backend: OpenGL
I/SceneView(  570): Optional library com.google.ar.sceneform.animation not present. Sceneform animation disabled
D/HwGalleryCacheManagerImpl(  570): mIsEffect:false
D/HwRTBlurUtils(  570): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@523c270, Nhwext : 0, get Blur : disable with , null
D/HwRTBlurUtils(  570): check blur style for HwPhoneWindow, themeResId : 0x0103023e, context : android.app.Presentation$3@523c270, Nhwext : 0, get Blur : disable with , null
D/OpenGLRenderer(  570):   HWUI Binary is  enabled
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(  570): arScenViewInit
I/HwApiCacheMangerEx(  570): apicache pi null
I/PressGestureDetector(  570): onAttached begin
I/PressGestureDetector(  570): onAttached end
I/PressGestureDetector(  570): HiTouch restricted: AboardArea.
D/mali_winsys(  570): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
I/com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView(  570): onActivityPaused
D/OpenGLRenderer(  570):   HWUI Binary is  enabled
D/HwCust  (  570): Create obj success use class android.app.HwCustActivityImpl
D/HwCust  (  570): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
V/ActivityThread(  570): ActivityThread,callActivityOnCreate
D/AndroidRuntime(  570): Shutting down VM
E/AndroidRuntime(  570): FATAL EXCEPTION: main
E/AndroidRuntime(  570): Process: com.difrancescogianmarco.arcore_flutter_plugin_example, PID: 570
E/AndroidRuntime(  570): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.difrancescogianmarco.arcore_flutter_plugin_example/com.google.ar.core.InstallActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(  570): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
E/AndroidRuntime(  570): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405)
E/AndroidRuntime(  570): 	at android.app.ActivityThread.-wrap12(Unknown Source:0)
E/AndroidRuntime(  570): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
E/AndroidRuntime(  570): 	at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime(  570): 	at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime(  570): 	at android.app.ActivityThread.main(ActivityThread.java:7523)
E/AndroidRuntime(  570): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  570): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime(  570): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/AndroidRuntime(  570): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter savedInstanceState
E/AndroidRuntime(  570): 	at com.difrancescogianmarco.arcore_flutter_plugin.ArCoreView$setupLifeCycle$1.onActivityCreated(Unknown Source:7)
E/AndroidRuntime(  570): 	at android.app.Application.dispatchActivityCreated(Application.java:208)
E/AndroidRuntime(  570): 	at android.app.Activity.onCreate(Activity.java:1110)
E/AndroidRuntime(  570): 	at com.google.ar.core.InstallActivity.onCreate(InstallActivity.java:4)
E/AndroidRuntime(  570): 	at android.app.Activity.performCreate(Activity.java:7383)
E/AndroidRuntime(  570): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
E/AndroidRuntime(  570): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
E/AndroidRuntime(  570): 	... 9 more
I/Process (  570): Sending signal. PID: 570 SIG: 9

**Comment by DK15** [comment]
I am getting same crash and listed [here](https://github.com/giandifra/arcore_flutter_plugin/issues/21).

**Comment by DK15** [comment]
@giandifra could you please let us know what could be the issue here ?

**Comment by DK15** [comment]
FWIW, I am using android emulator with below specs:

![Screen Shot 2019-11-18 at 11 36 31 AM](https://user-images.githubusercontent.com/16548367/69028500-2c6b7280-09f8-11ea-8c2d-74f329d4cdfa.png)

**Comment by DK15** [comment]
I followed all steps from [here](https://developers.google.com/ar/develop/java/emulator) which fixed the crash.

**Comment by giandifra** [comment]
I will add this info in readme, thanks
