### ISSUE TITLE
Build failed -> compilation error

### ISSUE THREAD

**Issue by SoensLars** [giandifra/arcore_flutter_plugin#201]
Hi everyone,

I'm currently working on a schoolproject with Flutter. It's the first time I'm using Flutter and I wanted to use the arcore_flutter_plugin. 
When I try to run my application I get a build error (see picture).
Can anyone help me with this problem?

Thanks in advance!

![image](https://user-images.githubusercontent.com/71964506/212160618-18d4428a-a079-4b0e-8a66-db48fb0b5193.png)

**Comment by IshitaArora-246** [comment]
got a similar error, did you find any work-around yet?

**Comment by SoensLars** [comment]
> 

I didn't find the solution to this error. Currently I'm using the ar_flutter_plugin which works fine. 
So you can maybe also try to use this plugin, I followed a tutorial on youtube (https://www.youtube.com/watch?v=hEwz2n1OkX8&ab_channel=INAXIA) about this plugin and now I can see objects in a AR-environment.

**Comment by giandifra** [comment]
The last version fix the error! I'm rewrite entire plugin! Stay tuned
