### ISSUE TITLE
Consider upgrading to SceneView from archived sceneform

### ISSUE THREAD

**Issue by MrCsabaToth** [giandifra/arcore_flutter_plugin#202]
I see that there's a branch `new-sceneform` (2 commits ahead, 6 commits behind master) which uses Thomas Gorisse's maintained SceneView fork. Possibly consider integrating SceneView which is the even newer and more actively maintained Kotlin version: https://sceneview.github.io/

**Comment by giandifra** [comment]
Yes, i Will migrate the plugin to the new sceneview!

**Comment by MrCsabaToth** [comment]
I don't have spare time now, but hopefully I'll be able to help, even if it's just testing. Looks like SceneView have a https://github.com/SceneView/sceneview-flutter repo, but as far as I can see it's a skeleton right now (meaning there's no unified API for iOS + Android if I see it correctly). I'm not sure what's the plan or effort of that repo, maybe forces can be unified?

**Comment by giandifra** [comment]
Exactly, i think it's a skeleton for flutter implementation! I would like to refactor my plugin to new sceneview.

**Comment by ThomasGorisse** [comment]
Hi @here.
Sure we can bring our common efforts to make it.
SceneView has a community with a Discord channel where we usually discuss.
Would you prefer keeping the project here or move it to the SceneView open community so it can be more visible and make everything at the same place?
https://github.com/SceneView

**Comment by giandifra** [comment]
> Hi @here. Sure we can bring our common efforts to make it. SceneView has a community with a Discord channel where we usually discuss. Would you prefer keeping the project here or move it to the SceneView open community so it can be more visible and make everything at the same place? https://github.com/SceneView

Hi, I was thinking of deprecating this and creating a new plugin, i can move it to the sceneview open community and deploy under my name on pub.dev, what do you think about? Any suggestions are appreciated! Thanks

**Comment by ThomasGorisse** [comment]
Sounds perfect!
I added you the GitHub rights. 
You should now be able to create the repository there.
Tell me if it's not the case.

**Comment by giandifra** [comment]
Thank you! 

Following [dart name convention](https://dart.dev/tools/pub/pubspec#name), i can create a plugin named `sceneview_flutter_plugin` or simply `sceneview_flutter`. Maybe the first to avoid mistake with the repo `sceneview-flutter`.  What do you think?

**Comment by ThomasGorisse** [comment]
You can use the existing `sceneview-project` it was just a test use case.

**Comment by giandifra** [comment]
> You can use the existing `sceneview-flutter` project it was just a test use case.

I have not permission to write in this [repo](https://github.com/SceneView/sceneview-flutter), can you give me the permission? 

Thanks

**Comment by ThomasGorisse** [comment]
Sorry about that. Can you make the test again?

**Comment by giandifra** [comment]
Ok, I did. I uploaded the demo version on pub.dev.
