### ISSUE TITLE
Support Geospatial API and Terrain Anchors

### ISSUE THREAD

**Issue by MrCsabaToth** [giandifra/arcore_flutter_plugin#203]
ARCore has now a Geospatial API feature (also Terrain Anchors help with elevation). I believe Thomas Gorisse's SceneView and SceneForm supports that, I'm not sure how things go on the iOS side, but since Unity has cross platform Goespatial API support there must be some way.

**Comment by giandifra** [comment]
This feature will be implemented in the new [plugin](https://pub.dev/packages/sceneview_flutter).
