### ISSUE TITLE
Can Not Launch Application | error: no suitable method found for add(ArcoreFlutterPlugin)

### ISSUE THREAD

**Issue by 4RSIM3R** [giandifra/arcore_flutter_plugin#22]
Hey i get some problem here
![why](https://user-images.githubusercontent.com/44225519/68912076-9f22e680-0789-11ea-802e-37fd2b9de7a2.JPG)

**Comment by vladir95** [comment]
#24 Should fix that issue

**Comment by djeriko** [comment]
Same issue

C:\projects\glory_places_ar\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:15: error: no suitable method found for add(ArcoreFlutterPlugin)
    flutterEngine.getPlugins().add(new com.difrancescogianmarco.arcore_flutter_plugin.ArcoreFlutterPlugin());
                              ^
    method PluginRegistry.add(FlutterPlugin) is not applicable
      (argument mismatch; ArcoreFlutterPlugin cannot be converted to FlutterPlugin)
    method PluginRegistry.add(Set<FlutterPlugin>) is not applicable
      (argument mismatch; ArcoreFlutterPlugin cannot be converted to Set<FlutterPlugin>)
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Gradle task assembleDebug failed with exit code 1
Launching lib\main.dart on Android SDK built for x86 in debug mode...
I/flutter (30542): 0.20325925
Exited (sigterm)
