### ISSUE TITLE
How to tap and place object and share on other device ?

### ISSUE THREAD

**Issue by DK15** [giandifra/arcore_flutter_plugin#23]
@giandifra I am exploring AR and your articles and repo has been helpful.
With current plugin, is it possible to:

1. Place the object when plane is detected ?
2. Share the object on other device at the same time ? or let's say draw a line or circle on screen and that is rendered on other device ?

Appreciate your response on this.

**Comment by giandifra** [comment]
Hi, 

1. Yes
2. No, this feature is not implemented [(Cloud Anchor)], 
(https://developers.google.com/ar/develop/java/cloud-anchors/overview-android)

I have every intention of implementing these functions (I only need time), of course the pull requests are welcome

**Comment by DK15** [comment]
Thanks for quick response. For 1, could you let me know how to achieve that or point me to reference (when plane is detected and tapped, the object will be placed there).

Thanks.
