### ISSUE TITLE
GLB file objectUrl

### ISSUE THREAD

**Issue by alterdieg0** [giandifra/arcore_flutter_plugin#28]
Hi, in the _remote object_ feature, the official documentation says that you can load either a GLTF or GLB file.

But in the plugin trying a link with a GLB at objectUrl in ArCoreReferenceNode it seems not to be working.

Any updates on that will be really helpful

**Comment by vextraz** [comment]
Just solved it changing RenderableSource.SourceType.GLTF2 to RenderableSource.SourceType.GLB at RenderableCustomFactory.kt

**Comment by YessineAmor** [comment]
@alterdieg0 could you please explain how to apply the changes to the plugin after changing from GLTF2 to GLB?

**Comment by alterdieg0** [comment]
@YessineAmor well, at least in the version of flutter I used that time you had to first import the package as it comes, then try to access the .kt files searching it in your files or through accessing the definitions of some of the classes that comes with the package such as ArCoreReferenceNode in your ide, and just editing the code I said and saving it, since the package is already imported in your flutter project the changes must be reflected with a hot restart

**Comment by BrutalCoding** [comment]
I've made a PR for this issue here https://github.com/giandifra/arcore_flutter_plugin/pull/78

**Comment by BrutalCoding** [comment]
> @YessineAmor well, at least in the version of flutter I used that time you had to first import the package as it comes, then try to access the .kt files searching it in your files or through accessing the definitions of some of the classes that comes with the package such as ArCoreReferenceNode in your ide, and just editing the code I said and saving it, since the package is already imported in your flutter project the changes must be reflected with a hot restart

This only works if you work alone and on the same machine every time. What you should actually do is fork this plugin, change the pubspec.yaml to reference your forked repo and of course change the code inside the repo itself. Now everyone will have the same plugin in your project.

E.g.
arcore_flutter_plugin:
    #path: ../arcore_flutter_plugin
    git:
      url: https://github.com/alterdiag0/arcore_flutter_plugin.git

**Comment by giandifra** [comment]
I will upload a new version on pub.dev in a few days! 
Thanks @BrutalCoding for #78
