### ISSUE TITLE
java.lang.IllegalStateException: Couldn't create Engine

### ISSUE THREAD

**Issue by Frixoe** [giandifra/arcore_flutter_plugin#5]
I'm trying to implement this plugin and my code is very similar to the example given.

However, whenever I start the app, I get this [output.](https://hastebin.com/onorobeneq.makefile) The line I think matters the most is: `java.lang.IllegalStateException: Couldn't create Engine`

`flutter doctor` says there are no issues.

Please help, I really need this to work. I've looked everywhere and couldn't find a solution. Thank you!

Here's some more info:
Operating System: **Manjaro i3 18.04**
CPU: **Intel Core i3** (this might be the issue)
Flutter Version: **v1.5.4**
Android SDK Version: **28.0.3**
Android Studio(which I don't use): **v3.4**

**Comment by Frixoe** [comment]
I just ran the example you have provided in the repo and go the same result: `java.lang.IllegalStateException: Couldn't create Engine`

**Comment by imvalient** [comment]
Hello,

I had the same issue, make sure you have set OpenGL API Level to "Render  Maximum" value by default.

![image](https://user-images.githubusercontent.com/5587234/88461729-4d993280-cea6-11ea-9269-5c7092101f88.png)
