### ISSUE TITLE
Sceneform is Dead ?

### ISSUE THREAD

**Issue by dariocavada** [giandifra/arcore_flutter_plugin#51]
Looking @ **ARCore**, I see that the latest version is the **1.17**

SceneForm is **Archived** so no further development on that.

[reddit is_sceneform_dead](https://www.reddit.com/r/androiddev/comments/glduwe/is_sceneform_dead/)

Are you thinking of moving forward with the development? 
To remove SceneForm? (SceneForm 1.16 is opensource and supports only the new gLTF format, 
(https://www.khronos.org/gltf/) 
Do you need help developing or testing or creating new examples?

**Comment by giandifra** [comment]
Hi, Yes Sceneform is Archived! 
For now i continue to improve this plugin using Sceneform waiting news about!  
Now I'm working on #89 to improve usability of plugin.
All help is appreciated
Thanks
