### ISSUE TITLE
How to disable plane detection?

### ISSUE THREAD

**Issue by msndvlpr** [giandifra/arcore_flutter_plugin#53]
When it detects planes showing white dots on surfaces becomes significantly slow and crashes after a few seconds! How can I disable detection of planes?

**Comment by BrutalCoding** [comment]
Check out this PR https://github.com/giandifra/arcore_flutter_plugin/pull/79

**Comment by giandifra** [comment]
I will upload new version on pub.dev in a few days. 
Thanks @BrutalCoding
