### ISSUE TITLE
app not working in release mode

### ISSUE THREAD

**Issue by iakshatbisht** [giandifra/arcore_flutter_plugin#54]
i built an application using arcore_flutter plugin. the app works perfectly in debug mode. but it is not working in release mode.
i have attached below the expected and observed outputs of the application kindly help me in resolving the issue.

This is what i get in release mode. i am unable to see the outputs.
![Screenshot (150)](https://user-images.githubusercontent.com/48102705/87962825-6df77480-cad5-11ea-9174-8a49e7dbf3a0.png)

This is what i get in debug mode. i can see my outputs(planets).
![Screenshot (151)](https://user-images.githubusercontent.com/48102705/87962833-718afb80-cad5-11ea-8c91-34abebc9a8df.png)

Kindly help.!!

**Comment by akshat102** [comment]
kindly refer to this issue stated above. it is for ar core flutter plugin

**Comment by akshat102** [comment]
Outputs of my flutter doctor -v command is as follows:

C:---------\AndroidStudioProjects\ar_core_example>flutter doctor -v
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18362.959], locale en-IN)
• Flutter version 1.17.3 at C:\flutter
• Framework revision b041144 (7 weeks ago), 2020-06-04 09:26:11 -0700
• Engine revision ee76268252
• Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at C:-------\AppData\Local\Android\sdk
• Platform android-29, build-tools 29.0.2
• Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
• All Android licenses accepted.

[√] Android Studio (version 4.0)
• Android Studio at C:\Program Files\Android\Android Studio
• Flutter plugin version 47.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
• VS Code at C:-----\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.11.0

[√] Connected device (2 available)
• GM1911 • 5a78b3ea • android-arm64 • Android 9 (API 28)
• Redmi Note 5 Pro • 92ec6a26 • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by akshat102** [comment]
??

**Comment by RobinLbt** [comment]
@iakshatbisht did you found a solution ? I'm experimenting the same problem. Working fine in debug mode but not in release

**Comment by RobinLbt** [comment]
It seems to be a problem when you use a image in a ARCoreNode.
When using simple shapes, it works in release mode (I've just tried it)
As soon as I use bytes for images, it doesn't work.
Here is the output I get in release mode : 
`E/flutter (27041): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: LateInitializationError: result
E/flutter (27041): #0      _LateInitializationError._throwNew (dart:core-patch/errors_patch.dart:505)
E/flutter (27041): #1      RenderObject.debugNeedsPaint (package:flutter/src/rendering/object.dart:2104)`

**Comment by RobinLbt** [comment]
Ok after a lot of testing I've found the problem.
Nothing to do with this plugin, it was because I was calling `boundary.debugNeedsPaint` in release mode.
You need to remove this call or to check before calling it in which mode you are at runtime with :
`if(kDebugMode)`

**Comment by naveenbharadwaj19** [comment]
@RobinLbt  Could you be more specific ? I'm facing the same problem it is working fine in debug mode not in release & profile

**Comment by naveenbharadwaj19** [comment]
@RobinLbt  So the problem is with `arcore_flutter_plugin `? Few months back even in release mode everything was working fine

**Comment by RobinLbt** [comment]
Yes I've tried everything and it seems like the plugin is creating the problem

**Comment by hanjinyu** [comment]
Is there any way to solve the problem you mentioned without using ar_flutter_plugin??
