### ISSUE TITLE
Local cache

### ISSUE THREAD

**Issue by tonyshkurenko** [giandifra/arcore_flutter_plugin#6]
I see in the example, that I can pass url of the 3d model and library will download it and display. But what if I want to manage cache by myself? I saw in docs, that I have to pass Uri in java/kotlin, how can I pass uri to file from Dart? I've only seen remote url example

**Comment by BrutalCoding** [comment]
Hi @tonyshkurenko,

Check out this PR https://github.com/giandifra/arcore_flutter_plugin/pull/78 that I just made.

In my use case, I download a remote .glb file, cache it myself, and use that cached path as object url. 

For example:
```
File glbDownloaded = await downloadFile('https://example.com/your_object.glb');
final node = ArCoreReferenceNode(
        name: 'node',
        objectUrl: "file://" + glbDownloaded.path
      );
```

The downloadFile() method checks if there is a cached version available on disk and returns the path to that file, else it will download the file first, cache it, and returns that path.
