### ISSUE TITLE
Image recognition

### ISSUE THREAD

**Issue by egemolu** [giandifra/arcore_flutter_plugin#60]
Hello giandifra, 
Currently, Does it possible to recognize and track images in flutter with your package? I have a project which is working on iOS. I need to scale it to Android. 

Thanks

**Comment by dariocavada** [comment]
The functionality is not mentioned in the documentation, but there is one example. 
You can use single image, multiple images or the `imgdb` database generated with the arcore img tool: 
`https://developers.google.com/ar/develop/c/augmented-images/arcoreimg`

The augmented images example:

`https://github.com/giandifra/arcore_flutter_plugin/blob/master/example/lib/screens/augmented_images.dart`
