### ISSUE TITLE
[Feature request] Add new shape 'ARCorePlane'? Add (png) image as material for ARCorePlane to display an image

### ISSUE THREAD

**Issue by BrutalCoding** [giandifra/arcore_flutter_plugin#66]
Hi,

Could anyone (or @giandifra himself) see if they can expand the current shapes (cube, cylinder, sphere) with a 'plane'? I would like to display an 2D image. Right now I'm showing a flat cube with the image as its texture, but it has a white reflectance that I can't get rid of. 

When using a (flat) cube with certain png's as its texture, I'm getting "Unhandled Exception: PlatformException(error, Invalid Bitmap: Bitmap's configuration must be ARGB_8888, but it was RGBA_F16, null)" when trying to display certain png's. These png's work fine with ARKit's Flutter plugin (https://pub.dev/packages/arkit_plugin). 

ARKit code example:
```
   final material = ARKitMaterial(
      lightingModelName: ARKitLightingModel.lambert,
      diffuse: ARKitMaterialProperty(image: imageUrl),
    );

    final geometry = ARKitPlane(
      materials: [material],
      width: 0.4,
      height: 0.4,
    );
    final node = ARKitNode(geometry: geometry, position: vector.Vector3(0, 0, -.8), name: 'some_name');
    _arkitController.add(node); 
```

I tried to add this feature myself but it seemed more involved than I hoped. If I got it working myself I'll close this issue, but I'm not that familiar with Kotlin and Android in general.

**Comment by giandifra** [comment]
Hi, I try to implement this feature in this week! 

Thank you

**Comment by BrutalCoding** [comment]
Looking forward to it!

**Comment by giandifra** [comment]
I'm releasing new version...

You can add image now:

```
 Future _addImage(ArCoreHitTestResult hit) async {
    final bytes =
        (await rootBundle.load('assets/earth.jpg')).buffer.asUint8List();

    final earth = ArCoreNode(
      image: ArCoreImage(bytes: bytes, width: 500, height: 500),
      position: hit.pose.translation + vector.Vector3(0.0, 0.0, 0.0),
      rotation: hit.pose.rotation + vector.Vector4(0.0, 0.0, 0.0, 0.0),
    );

    arCoreController.addArCoreNodeWithAnchor(earth);
  }
```

**Comment by BrutalCoding** [comment]
Tested it and can confirm it works flawlessly! Closing this issue now. I'll sponsor you today 👍

**Comment by Chos92** [comment]
Instead of the image could you display a video on it and play it on a loop ?

**Comment by BingHongLi** [comment]
> Instead of the image could you display a video on it and play it on a loop ?

me too,   i create a ARCoreMaterial instance,   try to give video byte to textureByte 

show imagedecode error..

**Comment by heyprincesingh** [comment]
> Tested it and can confirm it works flawlessly! Closing this issue now. I'll sponsor you today 👍

Hey Daniel! I know it is a bit long but can you please provide me the code you implemented for showing the 2D image onto the plane ground.

Here is the code I'm trying to implement. I want to show the image on ground(i.e. x-z Axiz) but unable to do so

`import 'package:arcore_flutter_plugin/arcore_flutter_plugin.dart';
import 'package:vector_math/vector_math_64.dart' as vector;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class ArEarthMapScreen extends StatefulWidget {
  const ArEarthMapScreen({super.key});

  @override
  State<ArEarthMapScreen> createState() => _ArEarthMapScreenState();
}

class _ArEarthMapScreenState extends State<ArEarthMapScreen> {
  ArCoreController? argumentedRealityCoreController;

  argumentedRealityViewCreated(ArCoreController coreController) {
    argumentedRealityCoreController = coreController;

    displayImagePlane(argumentedRealityCoreController!);
  }

  void displayImagePlane(ArCoreController coreController) async {
    final ByteData imageBytes = await rootBundle.load("assets/earth_map.jpg");

    final planeMaterial = ArCoreMaterial(
      color: Colors.blue,
      textureBytes: imageBytes.buffer.asUint8List(),
    );

    final image = ArCoreImage(
        bytes: imageBytes.buffer.asUint8List(), width: 100, height: 100);

    final node = ArCoreNode(
      image: image,
      position: vector.Vector3(0, 0, 0),
    );

    coreController.addArCoreNode(node);
  }

  @override
  void dispose() {
    argumentedRealityCoreController!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ArCoreView(
        onArCoreViewCreated: argumentedRealityViewCreated,
      ),
    );
  }
}
`

**Comment by heyprincesingh** [comment]
> Tested it and can confirm it works flawlessly! Closing this issue now. I'll sponsor you today 👍

Hey Daniel! I know it is a bit long but can you please provide me the code you implemented for showing the 2D image onto the plane ground.

Here is the code I'm trying to implement. I want to show the image on ground(i.e. x-z Axiz) but unable to do so

`
import 'package:arcore_flutter_plugin/arcore_flutter_plugin.dart';
import 'package:vector_math/vector_math_64.dart' as vector;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class ArEarthMapScreen extends StatefulWidget {
  const ArEarthMapScreen({super.key});

  @override
  State<ArEarthMapScreen> createState() => _ArEarthMapScreenState();
}

class _ArEarthMapScreenState extends State<ArEarthMapScreen> {
  ArCoreController? argumentedRealityCoreController;

  argumentedRealityViewCreated(ArCoreController coreController) {
    argumentedRealityCoreController = coreController;

    displayImagePlane(argumentedRealityCoreController!);
  }

  void displayImagePlane(ArCoreController coreController) async {
    final ByteData imageBytes = await rootBundle.load("assets/earth_map.jpg");

    final planeMaterial = ArCoreMaterial(
      color: Colors.blue,
      textureBytes: imageBytes.buffer.asUint8List(),
    );

    final image = ArCoreImage(
        bytes: imageBytes.buffer.asUint8List(), width: 100, height: 100);

    final node = ArCoreNode(
      image: image,
      position: vector.Vector3(0, 0, 0),
    );

    coreController.addArCoreNode(node);
  }

  @override
  void dispose() {
    argumentedRealityCoreController!.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ArCoreView(
        onArCoreViewCreated: argumentedRealityViewCreated,
      ),
    );
  }
}
`

**Comment by heyprincesingh** [comment]
> Tested it and can confirm it works flawlessly! Closing this issue now. I'll sponsor you today 👍

Hey Daniel! I know it is a bit long but can you please provide me the code you implemented for showing the 2D image onto the plane ground.

Here is the code I'm trying to implement. I want to show the image on ground(i.e. x-z Axiz) but unable to do so

`import 'package:arcore_flutter_plugin/arcore_flutter_plugin.dart';
import 'package:vector_math/vector_math_64.dart' as vector;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class ArEarthMapScreen extends StatefulWidget {
  const ArEarthMapScreen({super.key});

  @override
  State<ArEarthMapScreen> createState() => _ArEarthMapScreenState();
}

class _ArEarthMapScreenState extends State<ArEarthMapScreen> {
  ArCoreController? argumentedRealityCoreController;

  argumentedRealityViewCreated(ArCoreController coreController) {
    argumentedRealityCoreController = coreController;
    displayImagePlane(argumentedRealityCoreController!);
  }
  void displayImagePlane(ArCoreController coreController) async {
    final ByteData imageBytes = await rootBundle.load("assets/earth_map.jpg");
    final planeMaterial = ArCoreMaterial(
      color: Colors.blue,
      textureBytes: imageBytes.buffer.asUint8List(),
    );
    final image = ArCoreImage(
        bytes: imageBytes.buffer.asUint8List(), width: 100, height: 100);
    final node = ArCoreNode(
      image: image,
      position: vector.Vector3(0, 0, 0),
    );
    coreController.addArCoreNode(node);
  }
  @override
  void dispose() {
    argumentedRealityCoreController!.dispose();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ArCoreView(
        onArCoreViewCreated: argumentedRealityViewCreated,
      ),
    );
  }
}`
