### ISSUE TITLE
'scale' property of ArCoreReferenceNode doesn't work

### ISSUE THREAD

**Issue by rishikeshkchapekar** [giandifra/arcore_flutter_plugin#73]
**Code:** 

```
arCoreController.addArCoreNodeWithAnchor(
          ArCoreReferenceNode(
            name: "burger",
            object3DFileName:"Hamburger.sfb",
            scale: vector.Vector3(0.1,0.1,0.1),
            position: plane.pose.translation,
            rotation: plane.pose.rotation,
          ),
    
    );
```

**Issue:** 

The object is too big, so I'm trying to scale it down to 10% of the size. But `scale: vector.Vector3(0.1,0.1,0.1)` does not work. The object doesn't get scaled. Tried for multiple values, but the object remains the same size. 

Also tried it for various objects.

**Comment by giandifra** [comment]
Try transformable_node branch and follow #89
