### ISSUE TITLE
How do I change size of an object during runtime?

### ISSUE THREAD

**Issue by rishikeshkchapekar** [giandifra/arcore_flutter_plugin#77]
I understood from the examples how to change material properties. 

```spherenode.shape.materials.value = materials``` 

But now I want to be able to control the size of my node (in my case, a sphere). How do I do that, since ```spherenode.radius``` isn't a valid function and radius doesn't fall under material either

**Comment by giandifra** [comment]
I'm working to transformable node, you can see #89

**Comment by rishikeshkchapekar** [comment]
ok great!
