### ISSUE TITLE
Issue loading gltf model

### ISSUE THREAD

**Issue by pagach** [giandifra/arcore_flutter_plugin#85]
Hi,
I'm having issues loading my local gltf model.
I get an error:
Unable to load Renderable registryId='emoji0.gltf'
E/ModelRenderable(13531): java.util.concurrent.CompletionException: java.lang.AssertionError: No RCB file at uri: emoji0.gltf

Example model can be found here https://digital-reality.hr/sites/default/files/emoji0.gltf

It's not really plugin related cause some other models do work fine but was unable to find the solution elsewhere.

**Comment by BrutalCoding** [comment]
I haven’t tried out your model but as you say, some models seem to work. Can you try to open the model in Blender and export it through there in gltf? See if that makes any difference.

**Comment by BrutalCoding** [comment]
@pagach did you fix the issue?

**Comment by pagach** [comment]
No, not yet. But i'll close this issue since it's not really plugin related.
thx
