### ISSUE TITLE
Cannot display animations

### ISSUE THREAD

**Issue by MrRedbloX** [giandifra/arcore_flutter_plugin#95]
Hi,
I have been searching a way to play animations from .fbx files and I believe it's not handled on this plugin yet.
So I decided to look at the code and I added the feature.
Is there any way that I can show you what I have done I think it can be usefull for others.
Thanks.

![animation_demo](https://user-images.githubusercontent.com/32101242/101404006-524f0800-38d6-11eb-807e-2e8292ddfd37.gif)

**Comment by engor** [comment]
Hi, @MrRedbloX ! Can you share your code with animations? Via repository fork or so ?

**Comment by MrRedbloX** [comment]
Hi @engor, I have created a pull request.

**Comment by engor** [comment]
@MrRedbloX thanks! :)

**Comment by BrutalCoding** [comment]
Issue can be closed since you've made the feature yourself and contributed it as PR. Many thanks, I hope it gets reviewed and accepted 👍

**Comment by eduardoGo** [comment]
Hi, @MrRedbloX , thanks for is amazing feature!

Can you help me? I'm not able to animate the FBX models ...

I'm just use:

```
ArCoreReferenceNode(
        name: 'skull.sfb',
        object3DFileName: 'skull.sfb',
        position: plane.pose.translation,
        rotation: plane.pose.rotation,
        animationIndex: 0,
        animationRepeatNb: -1,
        );
```

the file skull.sfb is on `/android/app/src/main/assets`.
My skull.sfa:
```

{
  animations: [
    {
      clips: [
        {
          name: 'Take 001',
          runtime_name: 'skull',
        },
      ],
      path: './input/skull.fbx',
    },
  ],
  materials: [
    {
      name: 'skull_mat',
      parameters: [
        {
          baseColor: [
            1,
            1,
            1,
            1,
          ],
        },
        {
          baseColorMap: null,
        },
        {
          normalMap: null,
        },
        {
          interpolatedColor: null,
        },
        {
          metallic: 0,
        },
        {
          metallicMap: null,
        },
        {
          roughness: 1,
        },
        {
          roughnessMap: null,
        },
        {
          opacity: null,
        },
      ],
      source: './sceneform_sdk/default_materials/fbx_material.sfm',
    },
  ],
  model: {
    attributes: [
      'Position',
      'TexCoord',
      'Orientation',
      'BoneIndices',
      'BoneWeights',
    ],
    collision: {},
    file: './input/skull.fbx',
    name: 'skull',
    recenter: 'root',
  },
  version: '0.54:2',
}
```

The model appears, but the animation does not :(. Am I forgetting something? Can you send me any FBX and SFB files that you used?

**Comment by engor** [comment]
Probably, it's necessarily to implement `Sceneform SDK version 1.16.0` as described here: https://github.com/google-ar/sceneform-android-sdk
My first attempt to do it failed. :(

**Comment by eduardoGo** [comment]
Hi @engor, I found the bug. The animations don't work with controller.NodeWithAnchor. I tried use controller.addNode and the animations work fine.

Remote objects also don't work with controller.NodeWithAnchor, just with controller.addNode.

@giandifra
